In [1]:
import jovian


In [2]:
import torch


In [3]:
t1=torch.tensor(4.)
t1

tensor(4.)

In [4]:
t1.dtype

torch.float32

In [5]:
t2=torch.tensor([1.,2,3,4])
t2

tensor([1., 2., 3., 4.])

In [8]:
t3=torch.tensor([[5.,6],[7,8],[9,10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [13]:
t4=torch.tensor([[[11,12,13],[13,14,15]],[[15,16,17],[17,18,19.]]])
t4

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])

In [10]:
t4.dtype

torch.float32

In [12]:
print(t1)
t1.shape

tensor(4.)


torch.Size([])

In [14]:
print(t2)
t2.shape

tensor([1., 2., 3., 4.])


torch.Size([4])

In [15]:
print(t3)
t3.shape

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])


torch.Size([3, 2])

In [16]:
print(t4)
t4.shape

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])


torch.Size([2, 2, 3])

In [17]:
x=torch.tensor(3.)
w=torch.tensor(4.,requires_grad=True)
b=torch.tensor(5.,requires_grad=True)
x,w,b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [18]:
y=w*x+b
y

tensor(17., grad_fn=<AddBackward0>)

In [21]:
y.backward

<bound method Tensor.backward of tensor(17., grad_fn=<AddBackward0>)>

In [24]:
print('dy/dx:',x.grad)
print('dy/dw:',w.grad)
print('dy/db:',b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(2.)


In [31]:
t6=torch.full((3,2),42.)
t6

tensor([[42., 42.],
        [42., 42.],
        [42., 42.]])

In [35]:
t7=torch.cat((t3,t6))
t7

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [42., 42.],
        [42., 42.],
        [42., 42.]])

In [36]:
t8=torch.sin(t7)
t8

tensor([[-0.9589, -0.2794],
        [ 0.6570,  0.9894],
        [ 0.4121, -0.5440],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165]])

In [37]:
t9=t8.reshape(3,2,2)
t9

tensor([[[-0.9589, -0.2794],
         [ 0.6570,  0.9894]],

        [[ 0.4121, -0.5440],
         [-0.9165, -0.9165]],

        [[-0.9165, -0.9165],
         [-0.9165, -0.9165]]])

In [45]:
import numpy as np
x=np.array([[1,2],[3,4.]])
x

array([[1., 2.],
       [3., 4.]])

In [46]:
y=torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [47]:
x.dtype , y.dtype

(dtype('float64'), torch.float64)

In [50]:
z=y.numpy()
z

array([[1., 2.],
       [3., 4.]])

NameError: name 'git' is not defined